### ISSUE TITLE
Object detection with SNN

### ISSUE THREAD

**Issue by YangBain** [djsaunde/spiketorch#1]
Hi,
As we know that, nowadays, most works of SNN focus on Classification problems. So, do you think if it is possible to solve object detection problem with SNN since we need to solve regression problem in detection part.  Thank you very much.

**Comment by djsaunde** [comment]
Hi @YangBain,

I think it _may_ be possible to do object detection with SNNs; however, I'm not sure _how_. It should take some very clever way of framing the regression problem in terms of excitatory-inhibitory neuron interactions and STDP-based parameter updates.
