### ISSUE TITLE
Questions in groups.py

### ISSUE THREAD

**Issue by hqkhan** [djsaunde/spiketorch#8]
I had an issue with a line of code in groups.py. Specifically, line 96 in groups.py. I was confused as to why it is `self.refrac_count[self.s] = dt * self.refractory` and not `self.refrac_count[self.s] = self.refractory`. This is under LIFGroup class and under the "step" function. Why is there a "dt"? 

So, we are checking which neurons spiked and the ones that spiked will now have to wait for refractory period to end. I can see that in line 89 you are decrementing the counter by dt per time step which makes sense therefore, why is setting it not simply what I mentioned above?

Another question is for line `self.x[self.s.byte()] = 1.0` on line 104. Looking at the documentation for "byte()", it mentions that it is to cast tensor to byte type. Why are we casting it to byte? This way of picking elements usually has a boolean array when calling it. So I thought it should be `self.x[self.s] since self.s is an array of booleans.

**Comment by djsaunde** [comment]
Good catch, that's correct. I have been writing this in a rather haphazard fashion. I'll fix and add it to the current pull request.

I had to set it to `.byte()` previously since this caused an error in the code. Apparently, this is no longer happening. Very interesting!
